language: node_js

node_js:
  - "12"

services:
  - docker

cache: npm

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm run lint
  - npm run coverage

after_success:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

deploy:
  # deploy develop to the staging environment
  - provider: script
    script: bash deploy.sh development
    on:
      branch: development
  # deploy master to production
  - provider: script
    script: bash deploy.sh production
    on:
      branch: master
