version: "3"

services:
  tralert-transport-service:
    container_name: tralert-transport-service-dev
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - .:/app
      - /usr/src/app/node_modules
    command: npm run dev
